// Registro de usuario (público)
###
POST http://localhost:8080/usuarioslist
Content-Type: application/json

{
  "username": "Keniaaaa",
  "email": "keniaaa@gmail.com",
  "password": "12345",
  "role_id": 2
}

// Login (público)
###
POST http://localhost:8080/usuarioslist/login
Content-Type: application/json

{
  "email": "ivan@gmail.com",
  "password": "12345"
}

//Listar Usuarios por paginacion. (solo ADMIN)
###
GET http://localhost:8080/usuarioslist?page=2&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsInVzZXJuYW1lIjoiaXZhbiIsInJvbGVfaWQiOjMsImlhdCI6MTc2MTEwNDMxOCwiZXhwIjoxNzYxMTMzMTE4fQ.qjjVxuQVbT_lJyxJ4Lk70oPygzZkzduzysIYOZnur1I
Accept: application/json


// Eliminar usuario por ID (solo ADMIN)
###
DELETE http://localhost:8080/usuarioslist/7
Authorization: Bearer <TU_TOKEN>
Accept: application/json

// Actualizar usuario por ID (solo ADMIN)
###
PUT http://localhost:8080/usuarioslist/6
Authorization: Bearer <TU_TOKEN>
Content-Type: application/json

{
  "username": "Liss",
  "email": "emylis@gmail.com",
  "password": "123456",
  "role_id": 1
}

// Obtener todos los roles (solo ADMIN)
###
GET http://localhost:8080/usuarioslist/roles
Authorization: Bearer <TU_TOKEN>
Accept: application/json

//  LIst usuarios TODOS (solo ADMIN)
###
GET http://localhost:8080/usuarioslist/buscar
Authorization: Bearer <TU_TOKEN>
Accept: application/json

// Por email
###
GET http://localhost:8080/usuarioslist/buscar?email=emily
Authorization: Bearer <TU_TOKEN>
Accept: application/json

// Por rol
###
GET http://localhost:8080/usuarioslist/buscar?role_id=3
Authorization: Bearer <TU_TOKEN>
Accept: application/json

// Por email + rol
###
GET http://localhost:8080/usuarioslist/buscar?email=emily&role_id=2
Autho
