// Para probar el metodo GET, Resultado toda la lista de usuarios.----------------
###
GET  http://localhost:8080/usuarioslist HTTP/1.1

//Agregar un nuevo registro a la base de datos.------------------------------------
### 
POST http://localhost:8080/usuarioslist HTTP/1.1
Content-Type: application/json

{
  "username": "jemimi",
  "email": "jemimiara@gmail.com",
  "password": "123456",
  "role_id": 2
}

//Eliminar un regsitro de la base de datos. -----------------------------------------

###
DELETE http://localhost:8080/usuarioslist/5 HTTP/1.1

//Actualizar datos en la base de datos------------------------------------------------

###
PUT http://localhost:8080/usuarioslist/6 HTTP/1.1
Content-Type: application/json

{
  "username": "Libeth",
  "email": "emylis@gmail.com",
  "password": "123456",
  "role_id": 1
}

//Obtener por ID, SOLO UN USUARIO POR SU ID
### 
GET http://localhost:8080/usuarioslist/6

// Prueba del login --------------------------------------------------------------------
###
POST http://localhost:8080/usuarioslist/login
Content-Type: application/json

{
  "email": "emylis@gmail.com",
  "password": "123456"
}

### Usar token para ruta protegida (GET usuario por ID)
GET http://localhost:8080/usuarioslist/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJMaWJldGgiLCJyb2xlX2lkIjoxLCJpYXQiOjE3NTc3MDIzOTYsImV4cCI6MTc1NzcwNTk5Nn0.9RCNWnulzhngD9-02XY3rfuTMxvZ1R2mkztug16Jcb4


